/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpid_2020;

import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.saxon.s9api.SaxonApiException;
import net.sf.saxon.trans.XPathException;
import org.jdom2.Document;
import org.jdom2.Element;

/**
 *
 * @author Renato
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAddJogador = new javax.swing.JDialog();
        TextFieldNomeJogador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonAdicionarRemover = new javax.swing.JButton();
        jDialogRemJogador = new javax.swing.JDialog();
        TextFieldRemJogador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonremJogador = new javax.swing.JButton();
        jDialogEdita = new javax.swing.JDialog();
        jTextFieldEdit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextFieldEditNomeJogador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDialogPesquisa = new javax.swing.JDialog();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonPesquisa = new javax.swing.JButton();
        jDialogPesquisa2Valores = new javax.swing.JDialog();
        jTextFieldValorMinimo = new javax.swing.JTextField();
        jTextFieldValorMax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonPesquisa2Valores = new javax.swing.JButton();
        jDialogTransformacoes = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTransformacao = new javax.swing.JTextField();
        jButtonTransformação = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        MenuItemSair = new javax.swing.JMenuItem();
        jMenuXML = new javax.swing.JMenu();
        MenuItemVerXML = new javax.swing.JMenuItem();
        MenuItemAddJogador = new javax.swing.JMenuItem();
        MenuItemRemJogador = new javax.swing.JMenuItem();
        jMenuEditaXML = new javax.swing.JMenu();
        MenuItemEditaIdade = new javax.swing.JMenuItem();
        MenuItemEditaNacionalidade = new javax.swing.JMenuItem();
        MenuItemEditaClubeAtual = new javax.swing.JMenuItem();
        MenuItemEditaPeso = new javax.swing.JMenuItem();
        MenuItemEditaPrefPe = new javax.swing.JMenuItem();
        MenuItemEditaPos = new javax.swing.JMenuItem();
        MenuItemEditaVDC = new javax.swing.JMenuItem();
        MenuItemEditaEmpresário = new javax.swing.JMenuItem();
        MenuItemEditaEstadoAtual = new javax.swing.JMenuItem();
        jMenuPesquisarXML = new javax.swing.JMenu();
        MenuItemPesquisaJogador = new javax.swing.JMenuItem();
        MenuItemPesquisaClube = new javax.swing.JMenuItem();
        MenuItemPesquisaNacionalidade = new javax.swing.JMenuItem();
        MenuItemPesquisaPos = new javax.swing.JMenuItem();
        MenuItemPesquisaEstadoAtual = new javax.swing.JMenuItem();
        MenuItemPesquisaIdades = new javax.swing.JMenuItem();
        jMenuItemPesquisaVDC = new javax.swing.JMenuItem();
        jMenuValidar = new javax.swing.JMenu();
        jMenuItemValidaDTD = new javax.swing.JMenuItem();
        jMenuItemValidaXSD = new javax.swing.JMenuItem();
        jMenuTransformacoes = new javax.swing.JMenu();
        jMenuItemHTMLFotos = new javax.swing.JMenuItem();
        jMenuItemClube = new javax.swing.JMenuItem();
        jMenuItemNacionalidades = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItemTransformacaoEmpresario = new javax.swing.JMenuItem();
        jMenuItemTransformacaoEA = new javax.swing.JMenuItem();
        jMenuItemTransformacaoPosicao = new javax.swing.JMenuItem();

        jLabel2.setText("Nome do Jogador:");

        jButtonAdicionarRemover.setText("Adicionar");
        jButtonAdicionarRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogAddJogadorLayout = new javax.swing.GroupLayout(jDialogAddJogador.getContentPane());
        jDialogAddJogador.getContentPane().setLayout(jDialogAddJogadorLayout);
        jDialogAddJogadorLayout.setHorizontalGroup(
            jDialogAddJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddJogadorLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jDialogAddJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAddJogadorLayout.createSequentialGroup()
                        .addGroup(jDialogAddJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldNomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddJogadorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAdicionarRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jDialogAddJogadorLayout.setVerticalGroup(
            jDialogAddJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddJogadorLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldNomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButtonAdicionarRemover)
                .addGap(91, 91, 91))
        );

        jLabel3.setText("Nome do Jogador");

        jButtonremJogador.setText("Remover");
        jButtonremJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonremJogadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogRemJogadorLayout = new javax.swing.GroupLayout(jDialogRemJogador.getContentPane());
        jDialogRemJogador.getContentPane().setLayout(jDialogRemJogadorLayout);
        jDialogRemJogadorLayout.setHorizontalGroup(
            jDialogRemJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogRemJogadorLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jDialogRemJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldRemJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogRemJogadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonremJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jDialogRemJogadorLayout.setVerticalGroup(
            jDialogRemJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogRemJogadorLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldRemJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButtonremJogador)
                .addGap(27, 27, 27))
        );

        jLabel4.setText("Introduza Novo Valor:");

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Introduza o Nome do Jogador:");

        javax.swing.GroupLayout jDialogEditaLayout = new javax.swing.GroupLayout(jDialogEdita.getContentPane());
        jDialogEdita.getContentPane().setLayout(jDialogEditaLayout);
        jDialogEditaLayout.setHorizontalGroup(
            jDialogEditaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDialogEditaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jDialogEditaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldEdit)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldEditNomeJogador, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogEditaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jDialogEditaLayout.setVerticalGroup(
            jDialogEditaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditaLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldEditNomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addGap(80, 80, 80))
        );

        jLabel6.setText("Palavra de Pesquisa:");

        jButtonPesquisa.setText("Pesquisar");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogPesquisaLayout = new javax.swing.GroupLayout(jDialogPesquisa.getContentPane());
        jDialogPesquisa.getContentPane().setLayout(jDialogPesquisaLayout);
        jDialogPesquisaLayout.setHorizontalGroup(
            jDialogPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPesquisaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jDialogPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogPesquisaLayout.createSequentialGroup()
                        .addGroup(jDialogPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogPesquisaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jDialogPesquisaLayout.setVerticalGroup(
            jDialogPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPesquisaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButtonPesquisa)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jLabel7.setText("Valor Minimo:");

        jLabel8.setText("Valor Máximo:");

        jButtonPesquisa2Valores.setText("Pesquisar");
        jButtonPesquisa2Valores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisa2ValoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogPesquisa2ValoresLayout = new javax.swing.GroupLayout(jDialogPesquisa2Valores.getContentPane());
        jDialogPesquisa2Valores.getContentPane().setLayout(jDialogPesquisa2ValoresLayout);
        jDialogPesquisa2ValoresLayout.setHorizontalGroup(
            jDialogPesquisa2ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPesquisa2ValoresLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDialogPesquisa2ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogPesquisa2ValoresLayout.createSequentialGroup()
                        .addGroup(jDialogPesquisa2ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDialogPesquisa2ValoresLayout.createSequentialGroup()
                        .addGroup(jDialogPesquisa2ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldValorMinimo)
                            .addComponent(jTextFieldValorMax, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisa2Valores, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jDialogPesquisa2ValoresLayout.setVerticalGroup(
            jDialogPesquisa2ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPesquisa2ValoresLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogPesquisa2ValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisa2Valores))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jLabel9.setText(" Valor de Pesquisa:");

        jButtonTransformação.setText("Transformar");
        jButtonTransformação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransformaçãoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogTransformacoesLayout = new javax.swing.GroupLayout(jDialogTransformacoes.getContentPane());
        jDialogTransformacoes.getContentPane().setLayout(jDialogTransformacoesLayout);
        jDialogTransformacoesLayout.setHorizontalGroup(
            jDialogTransformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTransformacoesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jDialogTransformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTransformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogTransformacoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTransformação, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jDialogTransformacoesLayout.setVerticalGroup(
            jDialogTransformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTransformacoesLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTransformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTransformação)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        OutputTextArea.setColumns(20);
        OutputTextArea.setRows(5);
        jScrollPane1.setViewportView(OutputTextArea);

        jLabel1.setText("Output:");

        jMenuPrincipal.setText("Principal");

        MenuItemSair.setText("Sair");
        MenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSairActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(MenuItemSair);

        jMenuBar1.add(jMenuPrincipal);

        jMenuXML.setText("XML");

        MenuItemVerXML.setText("Ver Ficheiro XML");
        MenuItemVerXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemVerXMLActionPerformed(evt);
            }
        });
        jMenuXML.add(MenuItemVerXML);

        MenuItemAddJogador.setText("Adicionar Jogador");
        MenuItemAddJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddJogadorActionPerformed(evt);
            }
        });
        jMenuXML.add(MenuItemAddJogador);

        MenuItemRemJogador.setText("Remover Jogador");
        MenuItemRemJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemRemJogadorActionPerformed(evt);
            }
        });
        jMenuXML.add(MenuItemRemJogador);

        jMenuEditaXML.setText("Editar o XML");

        MenuItemEditaIdade.setText("Edita Idade");
        MenuItemEditaIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditaIdadeActionPerformed(evt);
            }
        });
        jMenuEditaXML.add(MenuItemEditaIdade);

        MenuItemEditaNacionalidade.setText("Edita Nacionalidade");
        MenuItemEditaNacionalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditaNacionalidadeActionPerformed(evt);
            }
        });
        jMenuEditaXML.add(MenuItemEditaNacionalidade);

        MenuItemEditaClubeAtual.setText("Edita Clube Atual");
        MenuItemEditaClubeAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditaClubeAtualActionPerformed(evt);
            }
        });
        jMenuEditaXML.add(MenuItemEditaClubeAtual);

        MenuItemEditaPeso.setText("Edita Peso");
        MenuItemEditaPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditaPesoActionPerformed(evt);
            }
        });
        jMenuEditaXML.add(MenuItemEditaPeso);

        MenuItemEditaPrefPe.setText("Edita Pé Preferido");
        MenuItemEditaPrefPe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditaPrefPeActionPerformed(evt);
            }
        });
        jMenuEditaXML.add(MenuItemEditaPrefPe);

        MenuItemEditaPos.setText("Edita Posição");
        MenuItemEditaPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditaPosActionPerformed(evt);
            }
        });
        jMenuEditaXML.add(MenuItemEditaPos);

        MenuItemEditaVDC.setText("Edita Valor de Contrato");
        MenuItemEditaVDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditaVDCActionPerformed(evt);
            }
        });
        jMenuEditaXML.add(MenuItemEditaVDC);

        MenuItemEditaEmpresário.setText("Edita Empresário");
        MenuItemEditaEmpresário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditaEmpresárioActionPerformed(evt);
            }
        });
        jMenuEditaXML.add(MenuItemEditaEmpresário);

        MenuItemEditaEstadoAtual.setText("Edita Estado Atual");
        MenuItemEditaEstadoAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditaEstadoAtualActionPerformed(evt);
            }
        });
        jMenuEditaXML.add(MenuItemEditaEstadoAtual);

        jMenuXML.add(jMenuEditaXML);

        jMenuPesquisarXML.setText("Pesquisar no XML");

        MenuItemPesquisaJogador.setText("Pesquisar Jogador");
        MenuItemPesquisaJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPesquisaJogadorActionPerformed(evt);
            }
        });
        jMenuPesquisarXML.add(MenuItemPesquisaJogador);

        MenuItemPesquisaClube.setText("Pesquisa Por Clube Atual");
        MenuItemPesquisaClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPesquisaClubeActionPerformed(evt);
            }
        });
        jMenuPesquisarXML.add(MenuItemPesquisaClube);

        MenuItemPesquisaNacionalidade.setText("Pesquisa Por Nacionalidade");
        MenuItemPesquisaNacionalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPesquisaNacionalidadeActionPerformed(evt);
            }
        });
        jMenuPesquisarXML.add(MenuItemPesquisaNacionalidade);

        MenuItemPesquisaPos.setText("Pesquisa Por Posição");
        MenuItemPesquisaPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPesquisaPosActionPerformed(evt);
            }
        });
        jMenuPesquisarXML.add(MenuItemPesquisaPos);

        MenuItemPesquisaEstadoAtual.setText("Pesquisa Por Estado Atual");
        MenuItemPesquisaEstadoAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPesquisaEstadoAtualActionPerformed(evt);
            }
        });
        jMenuPesquisarXML.add(MenuItemPesquisaEstadoAtual);

        MenuItemPesquisaIdades.setText("Pesquisa Por Idades");
        MenuItemPesquisaIdades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPesquisaIdadesActionPerformed(evt);
            }
        });
        jMenuPesquisarXML.add(MenuItemPesquisaIdades);

        jMenuItemPesquisaVDC.setText("Pesquisa Por Valor de Contrato");
        jMenuItemPesquisaVDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisaVDCActionPerformed(evt);
            }
        });
        jMenuPesquisarXML.add(jMenuItemPesquisaVDC);

        jMenuXML.add(jMenuPesquisarXML);

        jMenuBar1.add(jMenuXML);

        jMenuValidar.setText("Validar");

        jMenuItemValidaDTD.setText("DTD");
        jMenuItemValidaDTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemValidaDTDActionPerformed(evt);
            }
        });
        jMenuValidar.add(jMenuItemValidaDTD);

        jMenuItemValidaXSD.setText("XSD");
        jMenuItemValidaXSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemValidaXSDActionPerformed(evt);
            }
        });
        jMenuValidar.add(jMenuItemValidaXSD);

        jMenuBar1.add(jMenuValidar);

        jMenuTransformacoes.setText("Transformações");

        jMenuItemHTMLFotos.setText("XML -> HTML (Fotos)");
        jMenuItemHTMLFotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHTMLFotosActionPerformed(evt);
            }
        });
        jMenuTransformacoes.add(jMenuItemHTMLFotos);

        jMenuItemClube.setText("XML -> XML (Clube)");
        jMenuItemClube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClubeActionPerformed(evt);
            }
        });
        jMenuTransformacoes.add(jMenuItemClube);

        jMenuItemNacionalidades.setText("XML -> TXT (Nacionalidades)");
        jMenuItemNacionalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNacionalidadesActionPerformed(evt);
            }
        });
        jMenuTransformacoes.add(jMenuItemNacionalidades);

        jMenuItem4.setText("XML -> XML (Valor de Contrato)");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuTransformacoes.add(jMenuItem4);

        jMenuItemTransformacaoEmpresario.setText("XML -> XML (Empresario)");
        jMenuItemTransformacaoEmpresario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTransformacaoEmpresarioActionPerformed(evt);
            }
        });
        jMenuTransformacoes.add(jMenuItemTransformacaoEmpresario);

        jMenuItemTransformacaoEA.setText("XML -> TXT (Estado Atual)");
        jMenuItemTransformacaoEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTransformacaoEAActionPerformed(evt);
            }
        });
        jMenuTransformacoes.add(jMenuItemTransformacaoEA);

        jMenuItemTransformacaoPosicao.setText("XML -> HTML (Posição)");
        jMenuItemTransformacaoPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTransformacaoPosicaoActionPerformed(evt);
            }
        });
        jMenuTransformacoes.add(jMenuItemTransformacaoPosicao);

        jMenuBar1.add(jMenuTransformacoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuItemSairActionPerformed

    private void MenuItemVerXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemVerXMLActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("ID_XMLFile.xml");
        if (doc == null) {
            OutputTextArea.setText("Ficheiro não existe");
        } else {
            String output = XMLJDomFunctions.escreverDocumentoString(doc);
            OutputTextArea.setText(output);
        }
    }//GEN-LAST:event_MenuItemVerXMLActionPerformed

    private void MenuItemAddJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddJogadorActionPerformed
        // TODO add your handling code here:
        jDialogAddJogador.setSize(500, 350);
        jDialogAddJogador.setLocation(200, 200);
        jDialogAddJogador.setTitle("Adicionar Jogador");
        jDialogAddJogador.setVisible(true);
    }//GEN-LAST:event_MenuItemAddJogadorActionPerformed

    private void jButtonAdicionarRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarRemoverActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Jogador x = Jogador.cria_Jogador(TextFieldNomeJogador.getText());
            TextFieldNomeJogador.setText("");
            //Inicializa Doc XML
            Document doc = XMLJDomFunctions.lerDocumentoXML("ID_XMLFile.xml");
            //Chama a função para adicionar o livro ao XML
            doc = ModeloXML.adicionaJogador(x, doc);
            //grava o ficheiro XML em disco
            jDialogAddJogador.setVisible(false);
            if (doc != null) {
                XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "ID_XMLFile.xml");
                JOptionPane.showMessageDialog(this,
                        "Jogador adicionado com sucesso",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Jogador já existe",
                        "Informação",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SaxonApiException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAdicionarRemoverActionPerformed

    private void MenuItemRemJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemRemJogadorActionPerformed
        // TODO add your handling code here:
        jDialogRemJogador.setSize(500, 350);
        jDialogRemJogador.setLocation(200, 200);
        jDialogRemJogador.setTitle("Remover Jogador");
        jDialogRemJogador.setVisible(true);
    }//GEN-LAST:event_MenuItemRemJogadorActionPerformed

    private void jButtonremJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonremJogadorActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("ID_XMLFile.xml");
        String x = TextFieldRemJogador.getText();
        TextFieldRemJogador.setText("");
        //Chama a função para adicionar o livro ao XML
        doc = ModeloXML.removeJogador(x, doc);
        //grava o ficheiro XML em disco
        jDialogRemJogador.setVisible(false);
        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "ID_XMLFile.xml");

            JOptionPane.showMessageDialog(this,
                    "Jogador removido com sucesso",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Jogador não existe",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonremJogadorActionPerformed

    private void MenuItemEditaIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditaIdadeActionPerformed
        // TODO add your handling code here:
        jDialogEdita.setSize(500, 350);
        jDialogEdita.setLocation(200, 200);
        jDialogEdita.setTitle("Edita Idade");
        jDialogEdita.setVisible(true);
    }//GEN-LAST:event_MenuItemEditaIdadeActionPerformed

    private void MenuItemEditaNacionalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditaNacionalidadeActionPerformed
        // TODO add your handling code here:
        jDialogEdita.setSize(500, 350);
        jDialogEdita.setLocation(200, 200);
        jDialogEdita.setTitle("Edita Nacionalidade");
        jDialogEdita.setVisible(true);
    }//GEN-LAST:event_MenuItemEditaNacionalidadeActionPerformed

    private void MenuItemEditaClubeAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditaClubeAtualActionPerformed
        // TODO add your handling code here:
        jDialogEdita.setSize(500, 350);
        jDialogEdita.setLocation(200, 200);
        jDialogEdita.setTitle("Edita Clube Atual");
        jDialogEdita.setVisible(true);
    }//GEN-LAST:event_MenuItemEditaClubeAtualActionPerformed

    private void MenuItemEditaPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditaPesoActionPerformed
        // TODO add your handling code here:
        jDialogEdita.setSize(500, 350);
        jDialogEdita.setLocation(200, 200);
        jDialogEdita.setTitle("Edita Peso");
        jDialogEdita.setVisible(true);
    }//GEN-LAST:event_MenuItemEditaPesoActionPerformed

    private void MenuItemEditaPrefPeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditaPrefPeActionPerformed
        // TODO add your handling code here:
        jDialogEdita.setSize(500, 350);
        jDialogEdita.setLocation(200, 200);
        jDialogEdita.setTitle("Edita Pé Preferido");
        jDialogEdita.setVisible(true);
    }//GEN-LAST:event_MenuItemEditaPrefPeActionPerformed

    private void MenuItemEditaPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditaPosActionPerformed
        // TODO add your handling code here:
        jDialogEdita.setSize(500, 350);
        jDialogEdita.setLocation(200, 200);
        jDialogEdita.setTitle("Edita Posição");
        jDialogEdita.setVisible(true);
    }//GEN-LAST:event_MenuItemEditaPosActionPerformed

    private void MenuItemEditaVDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditaVDCActionPerformed
        // TODO add your handling code here:
        jDialogEdita.setSize(500, 350);
        jDialogEdita.setLocation(200, 200);
        jDialogEdita.setTitle("Edita Valor de Contrato");
        jDialogEdita.setVisible(true);
    }//GEN-LAST:event_MenuItemEditaVDCActionPerformed

    private void MenuItemEditaEmpresárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditaEmpresárioActionPerformed
        // TODO add your handling code here:
        jDialogEdita.setSize(500, 350);
        jDialogEdita.setLocation(200, 200);
        jDialogEdita.setTitle("Edita Empresário");
        jDialogEdita.setVisible(true);
    }//GEN-LAST:event_MenuItemEditaEmpresárioActionPerformed

    private void MenuItemEditaEstadoAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditaEstadoAtualActionPerformed
        // TODO add your handling code here:
        jDialogEdita.setSize(500, 350);
        jDialogEdita.setLocation(200, 200);
        jDialogEdita.setTitle("Edita Estado Atual");
        jDialogEdita.setVisible(true);
    }//GEN-LAST:event_MenuItemEditaEstadoAtualActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("ID_XMLFile.xml");
        String nome = jTextFieldEditNomeJogador.getText();
        String novoValor = jTextFieldEdit.getText();
        if (jDialogEdita.getTitle().equals("Edita Idade")) {
            int i = Integer.parseInt(novoValor);
            doc = ModeloXML.editaIdade(nome, i, doc);
        }
        if (jDialogEdita.getTitle().equals("Edita Nacionalidade")) {
            doc = ModeloXML.editaNacionalidade(nome, novoValor, doc);
        }
        if (jDialogEdita.getTitle().equals("Edita Clube Atual")) {
            doc = ModeloXML.editaClubeAtual(nome, novoValor, doc);
        }
        if (jDialogEdita.getTitle().equals("Edita Peso")) {
            double d = Double.parseDouble(novoValor);
            doc = ModeloXML.editaPeso(nome, d, doc);
        }
        if (jDialogEdita.getTitle().equals("Edita Pé Preferido")) {
            doc = ModeloXML.editaPrefPe(nome, novoValor, doc);
        }
        if (jDialogEdita.getTitle().equals("Edita Posição")) {
            doc = ModeloXML.editaPosicao(nome, novoValor, doc);
        }
        if (jDialogEdita.getTitle().equals("Edita Valor de Contrato")) {
            double d = Double.parseDouble(novoValor);
            doc = ModeloXML.editaVDC(nome, d, doc);
        }
        if (jDialogEdita.getTitle().equals("Edita Empresário")) {
            doc = ModeloXML.editaEmpresario(nome, novoValor, doc);
        }
        if (jDialogEdita.getTitle().equals("Edita Estado Atual")) {
            doc = ModeloXML.editaEstadoAtual(nome, novoValor, doc);
        }
        jDialogEdita.setVisible(false);
        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "ID_XMLFile.xml");
            JOptionPane.showMessageDialog(this,
                    "Valor alterado com sucesso",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Jogador não existe",
                    "Informação",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        jTextFieldEditNomeJogador.setText("");
        jTextFieldEdit.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("ID_XMLFile.xml");
        String pesquisa = jTextFieldSearch.getText();
        String res = null;
        if (jDialogPesquisa.getTitle().equals("Pesquisar Jogador")) {
            try {
                res = XPathFunctions.mostraInformaçãoRelevante("ID_XMLFile.xml", pesquisa);
            } catch (SaxonApiException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jDialogPesquisa.getTitle().equals("Pesquisar Por Clube Atual")) {
            try {
                res = XPathFunctions.mostraJogadoresPClube("ID_XMLFile.xml", pesquisa);
            } catch (SaxonApiException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jDialogPesquisa.getTitle().equals("Pesquisar Por Nacionalidade")) {
            try {
                res = XPathFunctions.mostraJogadoresNacionalidade("ID_XMLFile.xml", pesquisa);
            } catch (SaxonApiException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jDialogPesquisa.getTitle().equals("Pesquisar Por Posição")) {
            try {
                res = XPathFunctions.mostraJogadorPosicao("ID_XMLFile.xml", pesquisa);
            } catch (SaxonApiException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jDialogPesquisa.getTitle().equals("Pesquisar Por Estado Atual")) {
            try {
                res = XPathFunctions.mostraJogadorEstado("ID_XMLFile.xml", pesquisa);
            } catch (SaxonApiException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jDialogPesquisa.setVisible(false);
        if (res == null || res.equals("")) {
            res = "Sem resultado";
        }
        jTextFieldSearch.setText("");
        OutputTextArea.setText(res);
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void MenuItemPesquisaJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPesquisaJogadorActionPerformed
        // TODO add your handling code here:
        jDialogPesquisa.setSize(500, 350);
        jDialogPesquisa.setLocation(200, 200);
        jDialogPesquisa.setTitle("Pesquisar Jogador");
        jDialogPesquisa.setVisible(true);
    }//GEN-LAST:event_MenuItemPesquisaJogadorActionPerformed

    private void MenuItemPesquisaClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPesquisaClubeActionPerformed
        // TODO add your handling code here:
        jDialogPesquisa.setSize(500, 350);
        jDialogPesquisa.setLocation(200, 200);
        jDialogPesquisa.setTitle("Pesquisar Por Clube Atual");
        jDialogPesquisa.setVisible(true);
    }//GEN-LAST:event_MenuItemPesquisaClubeActionPerformed

    private void MenuItemPesquisaNacionalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPesquisaNacionalidadeActionPerformed
        // TODO add your handling code here:
        jDialogPesquisa.setSize(500, 350);
        jDialogPesquisa.setLocation(200, 200);
        jDialogPesquisa.setTitle("Pesquisar Por Nacionalidade");
        jDialogPesquisa.setVisible(true);
    }//GEN-LAST:event_MenuItemPesquisaNacionalidadeActionPerformed

    private void MenuItemPesquisaPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPesquisaPosActionPerformed
        // TODO add your handling code here:
        jDialogPesquisa.setSize(500, 350);
        jDialogPesquisa.setLocation(200, 200);
        jDialogPesquisa.setTitle("Pesquisar Por Posição");
        jDialogPesquisa.setVisible(true);
    }//GEN-LAST:event_MenuItemPesquisaPosActionPerformed

    private void MenuItemPesquisaEstadoAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPesquisaEstadoAtualActionPerformed
        // TODO add your handling code here:
        jDialogPesquisa.setSize(500, 350);
        jDialogPesquisa.setLocation(200, 200);
        jDialogPesquisa.setTitle("Pesquisar Por Estado Atual");
        jDialogPesquisa.setVisible(true);
    }//GEN-LAST:event_MenuItemPesquisaEstadoAtualActionPerformed

    private void jMenuItemValidaDTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemValidaDTDActionPerformed
        // TODO add your handling code here:
        try {
            int res = JDOMFunctions_Validar.validarDocumentoDTD("ID_XMLFile.xml", "ID_DTDFile.dtd");
            if (res == -1) {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro inválido por DTD",
                        "Informação Validação", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro válido por DTD",
                        "Informação Validação", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemValidaDTDActionPerformed

    private void jMenuItemValidaXSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemValidaXSDActionPerformed

        try {
            // TODO add your handling code here:
            int res = JDOMFunctions_Validar.validarDocumentoXSD("ID_XMLFile.xml", "ID_XSDFile.dtd");
            if (res == -1) {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro inválido por XSD",
                        "Informação Validação", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Ficheiro válido por XSD",
                        "Informação Validação", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemValidaXSDActionPerformed

    private void jButtonPesquisa2ValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisa2ValoresActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("ID_XMLFile.xml");
        Integer minVal = Integer.parseInt(jTextFieldValorMinimo.getText());
        Integer maxVal = Integer.parseInt(jTextFieldValorMax.getText());
        String res = null;
        if (jDialogPesquisa2Valores.getTitle().equals("Pesquisar Por Idades")) {
            try {
                res = XPathFunctions.mostraJogadorIdades("ID_XMLFile.xml", minVal, maxVal);
            } catch (SaxonApiException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jDialogPesquisa2Valores.getTitle().equals("Pesquisar Por Valor de Contrato")) {
            try {
                res = XPathFunctions.mostraJogadorVDM("ID_XMLFile.xml", minVal, maxVal);
            } catch (SaxonApiException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jDialogPesquisa2Valores.setVisible(false);
        if (res == null || res.equals("")) {
            res = "Sem resultado";
        }
        jTextFieldValorMinimo.setText("");
        jTextFieldValorMax.setText("");
        OutputTextArea.setText(res);
    }//GEN-LAST:event_jButtonPesquisa2ValoresActionPerformed

    private void MenuItemPesquisaIdadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPesquisaIdadesActionPerformed
        // TODO add your handling code here:
        jDialogPesquisa2Valores.setSize(500, 350);
        jDialogPesquisa2Valores.setLocation(200, 200);
        jDialogPesquisa2Valores.setTitle("Pesquisar Por Idades");
        jDialogPesquisa2Valores.setVisible(true);
    }//GEN-LAST:event_MenuItemPesquisaIdadesActionPerformed

    private void jMenuItemPesquisaVDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisaVDCActionPerformed
        // TODO add your handling code here:
        jDialogPesquisa2Valores.setSize(500, 350);
        jDialogPesquisa2Valores.setLocation(200, 200);
        jDialogPesquisa2Valores.setTitle("Pesquisar Por Valor de Contrato");
        jDialogPesquisa2Valores.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisaVDCActionPerformed

    private void jMenuItemClubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClubeActionPerformed
        // TODO add your handling code here:
        jDialogTransformacoes.setSize(500, 350);
        jDialogTransformacoes.setLocation(200, 200);
        jDialogTransformacoes.setTitle("Transforma Por Clube");
        jDialogTransformacoes.setVisible(true);

    }//GEN-LAST:event_jMenuItemClubeActionPerformed

    private void jMenuItemHTMLFotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHTMLFotosActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("ID_XMLFile.xml");
        if (doc != null) {
            Document novo = JDOMFunctions_XSLT.transformaDocumento(doc, "ID_XMLFile.xml", "transform1.xsl");
            XMLJDomFunctions.escreverDocumentoParaFicheiro(novo, "transformaImagens.html");
            doc = XMLJDomFunctions.lerDocumentoXML("transformaImagens.html");
            String t = XMLJDomFunctions.escreverDocumentoString(doc);
            OutputTextArea.setText(t);
            JOptionPane.showMessageDialog(this,
                    "Transformação feita com sucesso... a abrir browser...",
                    "XSLT para HTML", JOptionPane.INFORMATION_MESSAGE);
            String url = "transformaImagens.html";
            File htmlFile = new File(url);
            try {
                Desktop.getDesktop().browse(htmlFile.toURI());
            } catch (IOException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItemHTMLFotosActionPerformed

    private void jMenuItemNacionalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNacionalidadesActionPerformed
        // TODO add your handling code here:
        jDialogTransformacoes.setSize(500, 350);
        jDialogTransformacoes.setLocation(200, 200);
        jDialogTransformacoes.setTitle("Transforma Por Nacionalidade");
        jDialogTransformacoes.setVisible(true);
    }//GEN-LAST:event_jMenuItemNacionalidadesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Document doc = XMLJDomFunctions.lerDocumentoXML("ID_XMLFile.xml");
        if (doc != null) {
            Document novo = JDOMFunctions_XSLT.transformaDocumento(doc, "ID_XMLFile.xml", "transform4.xsl");
            XMLJDomFunctions.escreverDocumentoParaFicheiro(novo, "transformaContratos.xml");
            doc = XMLJDomFunctions.lerDocumentoXML("transformaContratos.xml");
            String t = XMLJDomFunctions.escreverDocumentoString(doc);
            OutputTextArea.setText(t);
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemTransformacaoEmpresarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTransformacaoEmpresarioActionPerformed
        jDialogTransformacoes.setSize(500, 350);
        jDialogTransformacoes.setLocation(200, 200);
        jDialogTransformacoes.setTitle("Transforma Por Empresario");
        jDialogTransformacoes.setVisible(true);
    }//GEN-LAST:event_jMenuItemTransformacaoEmpresarioActionPerformed

    private void jMenuItemTransformacaoEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTransformacaoEAActionPerformed
        // TODO add your handling code here:
        jDialogTransformacoes.setSize(500, 350);
        jDialogTransformacoes.setLocation(200, 200);
        jDialogTransformacoes.setTitle("Transforma Por Estado Atual");
        jDialogTransformacoes.setVisible(true);
    }//GEN-LAST:event_jMenuItemTransformacaoEAActionPerformed

    private void jMenuItemTransformacaoPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTransformacaoPosicaoActionPerformed
        try {
            // TODO add your handling code here:
            SaxonFunctions_XQuery.xQueryToHtml("transformacaoPosicao.html", "transform7.xql");
            Document doc = XMLJDomFunctions.lerDocumentoXML("transformacaoPosicao.html");
            String t = XMLJDomFunctions.escreverDocumentoString(doc);
            JOptionPane.showMessageDialog(this,
                    "Transformação feita com sucesso... a abrir browser...",
                    "XSLT para HTML", JOptionPane.INFORMATION_MESSAGE);
            String url = "transformacaoPosicao.html";
            File htmlFile = new File(url);
            try {
                Desktop.getDesktop().browse(htmlFile.toURI());
            } catch (IOException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (XPathException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemTransformacaoPosicaoActionPerformed

    private void jButtonTransformaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransformaçãoActionPerformed
        // TODO add your handling code here:
        Element raiz = new Element("Valor");
        Document doc = new Document(raiz);
        raiz.addContent(jTextFieldTransformacao.getText());
        XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "valor.xml");
        if (jDialogTransformacoes.getTitle().equals("Transforma Por Clube")) {
            try {
                SaxonFunctions_XQuery.xQueryToXml("transformaClubes.xml", "transform2V2.xql");
                doc = XMLJDomFunctions.lerDocumentoXML("transformaClubes.xml");
                String t = XMLJDomFunctions.escreverDocumentoString(doc);
                OutputTextArea.setText(t);
            } catch (XPathException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jDialogTransformacoes.getTitle().equals("Transforma Por Nacionalidade")) {
            try {
                SaxonFunctions_XQuery.xQueryToText("transformacaoNacionalidade.txt", "transform3V2.xql");
                Scanner ler = new Scanner(new FileInputStream("transformacaoNacionalidade.txt"));
                StringBuilder texto = new StringBuilder();
                String linha;
                while (ler.hasNextLine()) {
                    linha = ler.nextLine();
                    texto = texto.append(linha).append("\n");
                }
                ler.close();
                OutputTextArea.setText(texto.toString());
            } catch (XPathException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jDialogTransformacoes.getTitle().equals("Transforma Por Empresario")) {
            try {
                // TODO add your handling code here:
                SaxonFunctions_XQuery.xQueryToXml("transformacaoEmpresario.xml", "transform5.xql");
                doc = XMLJDomFunctions.lerDocumentoXML("transformacaoEmpresario.xml");
                String t = XMLJDomFunctions.escreverDocumentoString(doc);
                OutputTextArea.setText(t);
            } catch (XPathException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jDialogTransformacoes.getTitle().equals("Transforma Por Estado Atual")) {
            try {
                // TODO add your handling code here:
                SaxonFunctions_XQuery.xQueryToText("transformacaoEstadoAtual.txt", "transform6.xql");
                Scanner ler = new Scanner(new FileInputStream("transformacaoEstadoAtual.txt"));
                StringBuilder texto = new StringBuilder();
                String linha;
                while (ler.hasNextLine()) {
                    linha = ler.nextLine();
                    texto = texto.append(linha).append("\n");
                }
                ler.close();
                OutputTextArea.setText(texto.toString());
            } catch (XPathException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jDialogTransformacoes.setVisible(false);
        jTextFieldTransformacao.setText("");
    }//GEN-LAST:event_jButtonTransformaçãoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemAddJogador;
    private javax.swing.JMenuItem MenuItemEditaClubeAtual;
    private javax.swing.JMenuItem MenuItemEditaEmpresário;
    private javax.swing.JMenuItem MenuItemEditaEstadoAtual;
    private javax.swing.JMenuItem MenuItemEditaIdade;
    private javax.swing.JMenuItem MenuItemEditaNacionalidade;
    private javax.swing.JMenuItem MenuItemEditaPeso;
    private javax.swing.JMenuItem MenuItemEditaPos;
    private javax.swing.JMenuItem MenuItemEditaPrefPe;
    private javax.swing.JMenuItem MenuItemEditaVDC;
    private javax.swing.JMenuItem MenuItemPesquisaClube;
    private javax.swing.JMenuItem MenuItemPesquisaEstadoAtual;
    private javax.swing.JMenuItem MenuItemPesquisaIdades;
    private javax.swing.JMenuItem MenuItemPesquisaJogador;
    private javax.swing.JMenuItem MenuItemPesquisaNacionalidade;
    private javax.swing.JMenuItem MenuItemPesquisaPos;
    private javax.swing.JMenuItem MenuItemRemJogador;
    private javax.swing.JMenuItem MenuItemSair;
    private javax.swing.JMenuItem MenuItemVerXML;
    private javax.swing.JTextArea OutputTextArea;
    private javax.swing.JTextField TextFieldNomeJogador;
    private javax.swing.JTextField TextFieldRemJogador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdicionarRemover;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonPesquisa2Valores;
    private javax.swing.JButton jButtonTransformação;
    private javax.swing.JButton jButtonremJogador;
    private javax.swing.JDialog jDialogAddJogador;
    private javax.swing.JDialog jDialogEdita;
    private javax.swing.JDialog jDialogPesquisa;
    private javax.swing.JDialog jDialogPesquisa2Valores;
    private javax.swing.JDialog jDialogRemJogador;
    private javax.swing.JDialog jDialogTransformacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEditaXML;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemClube;
    private javax.swing.JMenuItem jMenuItemHTMLFotos;
    private javax.swing.JMenuItem jMenuItemNacionalidades;
    private javax.swing.JMenuItem jMenuItemPesquisaVDC;
    private javax.swing.JMenuItem jMenuItemTransformacaoEA;
    private javax.swing.JMenuItem jMenuItemTransformacaoEmpresario;
    private javax.swing.JMenuItem jMenuItemTransformacaoPosicao;
    private javax.swing.JMenuItem jMenuItemValidaDTD;
    private javax.swing.JMenuItem jMenuItemValidaXSD;
    private javax.swing.JMenu jMenuPesquisarXML;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JMenu jMenuTransformacoes;
    private javax.swing.JMenu jMenuValidar;
    private javax.swing.JMenu jMenuXML;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEdit;
    private javax.swing.JTextField jTextFieldEditNomeJogador;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldTransformacao;
    private javax.swing.JTextField jTextFieldValorMax;
    private javax.swing.JTextField jTextFieldValorMinimo;
    // End of variables declaration//GEN-END:variables
}
